apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-deployment
  namespace: calendar
  labels:
    app: cal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cal
  template:
    metadata:
      labels:
        app: cal
    spec:
      restartPolicy: Always
      containers:
        - name: cal
          image: docker.io/library/google-cal:latest
          ports:
            - containerPort: 3001
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: ".5"
              memory: "1G"
          env:
            # - name: MONGO_INITDB_ROOT_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-secret
            #       key: mongo-root-username
            # - name: MONGO_INITDB_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-secret
            #       key: mongo-root-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-init-database
            - name: MONGO_URL
              value: mongo-service
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MONGO_PORT
