apiVersion: v1
kind: Service
metadata:
  name: cal-service
  namespace: calendar
spec:
  selector:
    app: cal
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      nodePort: 30000
  type: LoadBalancer
