apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: calendar
spec:
  selector:
    app: jenkins-stateful-set
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30002
  type: LoadBalancer
