apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-stateful-set
  namespace: calendar
  labels:
    app: jenkins-stateful-set
spec:
  selector:
    matchLabels:
      app: jenkins-stateful-set
  serviceName: jenkins-service
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-stateful-set
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
        - name: jenkins-stateful-set
          image: docker.io/jenkins/jenkins:2.346.3-jdk11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-claim
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-claim
          persistentVolumeClaim:
            claimName: jenkins-claim
