apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  namespace: calendar
spec:
  storageClassName: jenkins-storage
  resources:
    requests:
      storage: "20G"
    limits:
      storage: "30G"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
