apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: calendar
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  type: ClusterIP
