apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-claim
  namespace: calendar
  labels:
    name: persistent-claim

spec:
  storageClassName: mongo-storage
  resources:
    requests:
      storage: "5"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
