apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
    storage: "30G"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-storage
  hostPath:
    path: /home/amirho/kubernetes-volumes/mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
spec:
  capacity:
    storage: "30G"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-storage
  hostPath:
    path: /home/amirho/kubernetes-volumes/jenkins
