apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: calendar
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-init-database: dGVzdA==
